//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EventTypes;
namespace WpfWcfDashboard.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://Microsoft.ServiceModel.WcfObserver", ConfigurationName = "ServiceReference1.IWCFObserver", CallbackContract = typeof(WpfWcfDashboard.ServiceReference1.IWCFObserverCallback))]
    public interface IWCFObserver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/Subscribe", ReplyAction="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/Unsubscribe", ReplyAction="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/UnsubscribeResponse")]
        void Unsubscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFObserverCallback
    {
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/OnCompleted")]
        void OnCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/OnError")]
        void OnError(System.Exception error);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.ServiceModel.WcfObserver/IWCFObserver/OnNext")]
        void OnNext(OutputEvent value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFObserverChannel : WpfWcfDashboard.ServiceReference1.IWCFObserver, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFObserverClient : System.ServiceModel.DuplexClientBase<WpfWcfDashboard.ServiceReference1.IWCFObserver>, WpfWcfDashboard.ServiceReference1.IWCFObserver {
        
        public WCFObserverClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFObserverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFObserverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFObserverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFObserverClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
    }
}
