//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EventTypes;
namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://Microsoft.ServiceModel.WcfObservable", ConfigurationName = "ServiceReference1.IWCFObservable")]
    public interface IWCFObservable {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://Microsoft.ServiceModel.WcfObservable/IWCFObservable/OnCompleted")]
        void OnCompleted();

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://Microsoft.ServiceModel.WcfObservable/IWCFObservable/OnError")]
        void OnError(System.Exception error);

        [System.ServiceModel.OperationContractAttribute(Action = "http://Microsoft.ServiceModel.WcfObservable/IWCFObservable/OnNext", ReplyAction = "http://Microsoft.ServiceModel.WcfObservable/IWCFObservable/OnNextResponse")]
        void OnNext(InputEvent value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFObservableChannel : WcfClient.ServiceReference1.IWCFObservable, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFObservableClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IWCFObservable>, WcfClient.ServiceReference1.IWCFObservable {
        
        public WCFObservableClient() {
        }
        
        public WCFObservableClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFObservableClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFObservableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFObservableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OnCompleted() {
            base.Channel.OnCompleted();
        }
        
        public void OnError(System.Exception error) {
            base.Channel.OnError(error);
        }
        
        public void OnNext(InputEvent value) {
            base.Channel.OnNext(value);
        }
    }
}
